---
################
# Build & Test #
################

kind: pipeline
name: build_test

steps:
  # Build and test with Gradle
  - name: build
    image: gradle:7.2.0-jdk17
    environment:
      ORG_GRADLE_PROJECT_mavenUser:
        from_secret: maven-user
      ORG_GRADLE_PROJECT_mavenPassword:
        from_secret: maven-password
    commands:
      # BUILD
      - gradle assemble
      # TEST
      - gradle check
trigger:
  branch:
    - master
    - develop
  event:
    - pull_request
    - push